asset_font_genshin: str = 'assets/fonts/genshin.ttf'
asset_icon_database: str = 'assets/icons/database.svg'
asset_icon_manufacturing: str = 'assets/icons/manufacturing.svg'
asset_icon_group: str = 'assets/icons/group.svg'
asset_icon_person: str = 'assets/icons/person.svg'
asset_icon_route: str = 'assets/icons/route.svg'
asset_img_banner: str = 'assets/images/banner.png'
asset_img_compass: str = 'assets/images/compass.png'
asset_path_agencies: str = 'assets/agencies'
asset_path_brands: str = 'assets/brands'
asset_path_markers: str = 'assets/markers'
asset_path_vehicles: str = 'assets/vehicles'

codegen_template_kml_gtfs: str = 'codegen/kml/gtfs.jinja'
codegen_template_kml_raid: str = 'codegen/kml/raid.jinja'

color_raid_route: str = 'ff61b1'

compileddata_map: str = 'data/js/map.min.js'
compileddata_players: str = 'data/js/players_data.min.js'
compileddata_lines: str = 'data/js/lines_data.min.js'
compileddata_stops: str = 'data/js/stops_data.min.js'
compileddata_vehicles: str = 'data/js/vehicles_data.min.js'

controller_announcements: str = 'assets/scripts/announcements.js'
controller_archive: str = 'assets/scripts/archive.js'
controller_common: str = 'assets/scripts/common.js'
controller_map: str = 'assets/scripts/map.js'
controller_raids: str = 'assets/scripts/raids.js'

document_announcements: str = 'announcements.html'
document_archive: str = 'archive.html'
document_map: str = 'index.html'
document_raids: str = 'raids.html'

lexmap_polish: str = 'assets/lang/alphabet/pl_pl.txt'

mapdata_paths_lines: str = 'data/map/lines'
mapdata_paths_raids: str = 'data/map/raids'

playerdata_file_ev_stops: str = 'ev_stops.csv'
playerdata_file_lines: str = 'lines.csv'
playerdata_file_stops: str = 'stops.csv'
playerdata_file_terminals: str = 'terminals.csv'
playerdata_file_vehicles: str = 'vehicles.csv'
playerdata_path: str = 'playerdata'

raiddata_path: str = 'raiddata'

report_gtfs: str = 'reports/gtfs_update.txt'

stylesheet_announcements: str = 'assets/stylesheets/announcements.css'
stylesheet_archive: str = 'assets/stylesheets/archive.css'
stylesheet_common: str = 'assets/stylesheets/common.css'
stylesheet_map: str = 'assets/stylesheets/map.css'
stylesheet_raids: str = 'assets/stylesheets/raids.css'

rawdata_announcements: str = 'data/raw/announcements.csv'
rawdata_carriers: str = 'data/raw/carriers.csv'
rawdata_lines: str = 'data/raw/lines.csv'
rawdata_players: str = 'data/raw/players.csv'
rawdata_raids: str = 'data/raw/raids.csv'
rawdata_regions: str = 'data/raw/regions.json'
rawdata_routes: str = 'data/raw/routes.csv'
rawdata_scheduled_changes: str = 'data/raw/scheduled_changes.csv'
rawdata_stop_times: str = 'data/raw/stop_times.csv'
rawdata_stops: str = 'data/raw/stops.csv'
rawdata_terminals: str = 'data/raw/tramway_terminals.csv'
rawdata_trips: str = 'data/raw/trips.csv'
rawdata_vehicles: str = 'data/raw/vehicles.csv'
rawdata_vehicle_models: str = 'data/raw/vehicle_models.csv'

templates_path_announcements: str = 'templates/announcements/_articles'

tmpdata_gtfs: str = 'data/gtfs.zip'

url_announcements_mpk: str = 'https://www.mpk.poznan.pl/komunikaty/'
url_announcements_ztm_1: str = 'https://www.ztm.poznan.pl/komunikaty/'
url_announcements_ztm_2: str = 'https://www.ztm.poznan.pl/komunikaty/page/2/'
url_announcements_ztm_3: str = 'https://www.ztm.poznan.pl/komunikaty/page/3/'
url_material_icons: str = 'https://fonts.googleapis.com/icon?family=Material+Icons'
url_material_symbols: str = 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0'
url_script_nunjucks: str = 'https://mozilla.github.io/nunjucks/files/nunjucks.min.js'
url_ztm_gtfs: str = 'https://www.ztm.poznan.pl/pl/dla-deweloperow/getGTFSFile'
